rho-devel/rho

src/include/CXXR/ListFrame.hpp
src/include/CXXR/jit/CompiledFrame.hpp
src/main/ListFrame.cpp
src/main/jit/CompiledFrame.cpp

vector with overflow going to a hash map.
This removes the linked-list that was previously used in all cases and
should result in better performance both small frames and very large ones.
Make CompiledFrame inherit from the new ListFrame, which apart from
lacking a FrameDescriptor has an almost identical implementation now.

Change the implementation of ListFrame to store elements in a fixed-size

---

src/include/Rinternals.h
src/main/provenance_do.cpp

this fixes the multiple definitions of Rf_allocVector error on Ubuntu 14.04, gcc 4.8.4, and fixes building using --enable-provenance-tracking

fix provenance build, using ./configure --enable-provenance-tracking

---

tests/CXXR/Makefile.in

Some regression tests compare output error/warning messages. Comparison works for english locale only.

Fix for localized regression tests

---

.travis.yml
.ubsan_suppressions
README.md
configure
configure.ac
src/include/rho/ConsCell.hpp
src/include/rho/jit/Runtime.hpp
src/main/ArgList.cpp
src/main/eval.cpp
src/main/jit/CompiledExpression.cpp
src/main/jit/Makefile.in
src/main/jit/Runtime.cpp
tests/rho/MCJITMemoryManagerTests.cpp

Adds the following compilers to the travis config:
- gcc 4.9 (no longer an allowed failure)
- gcc 5.0
- clang 3.6
- clang 3.7 (segfaults, tagged as allowed failure)
- clang 3.8
- clang 3.8 with asan
- clang 3.8 with ubsan (segfaults, tagged as allowed failure)
Plus some minor code changes to make the code compile on those platforms and remove undefined behaviour.

Support and test more compilers

---

src/include/rho/FixedVector.hpp
src/include/rho/GCNode.hpp
src/include/rho/MemoryBank.hpp
src/library/base/R/allocstats.R
src/main/GCNode.cpp
src/main/Makefile.in
src/main/MemoryBank.cpp
src/main/String.cpp
src/main/allocstats.cpp
src/main/basedecl.h
src/main/registration.cpp

This adds a .Call function called "allocstats" that can be used to
get allocation statistics. It returns a list vector of three columns:
allocation size, number of allocations, and number of frees.

Add internal allocstats function

---

bench/.gitignore
bench/report.R
bench/runbench.py

This adds a Python script (bench/runbench.py) for benchmarking Rho. The
script attempts to automate the building and benchmarking of a specific
version of Rho. The goal is to make it simpler to gather performance
metrics and reduce the risk for human error affecting benchmark results.
The benchmark script takes as argument a Git reference for the version
of Rho to benchmark, it also benchmarks CR as a baseline for performance
comparison.

Add benchmarking script

---

bench/report.R
bench/runbench.py

The benchmark report script now generates one graph for each benchmark.
Also added a command line argument to specify an alternate output
directory for the report script.
Added generation of tables.pdf with detailed statistics for each
benchmark.
Filtered out qr.R because it fails to run, and
shootout/mandelbrot/mandelbrot.R because it conflicts with
riposte/mandelbrot.R.

Updated benchmark set and benchmark report script

---

bench/runbench.py

This fixes an error that caused the benchmark script to not correctly
clean the build directory before building Rho.

Fix error in benchmark script

---

bench/.gitignore
bench/incremental.R

This adds a helper script for benchmarking a small number of commits at
a time.

Add incremental benchmark script

---

.travis.yml

* Get clang 3.7 and 3.8 from the LLVM ppa, not sid.
* Add gcc 6.1 to the set of tested compilers

Fix compilers on travis

---

src/include/rho/GCNode.hpp
src/main/GCNode.cpp
src/main/WeakRef.cpp

This splits out the counting feature of GCNode::Marker into a separate
derived class.

Separate counting marker GCNode::CountingMarker

---

src/include/rho/GCNode.hpp
src/main/GCNode.cpp

Removes the "on stack" flag test immediately after clearing it.
Also changed clearOnStackBit() to directly add to the moribund list
without testing s_on_stack_bits_correct which is always false when
calling clearOnStackBit().

Remove redundant on stack test

---

bench/.gitignore
bench/incremental.R
bench/runbench.py

The script runbench.py now fetches commits from the remote repository
before trying to switch revision. This fix makes it possible to
benchmark new commits.
The spectral-norm benchmark has been disabled because it takes too long
to run.
Running benchmarks via incremental.R inherits R environment variables
and affects benchmark results. The script has been changed to instead
write an output file containing the commit hashes to benchmark, the
output can then be passed to runbench.py.

Fix error in runbench.py and update incremental.R

---

src/include/rho/BinaryFunction.hpp
src/include/rho/FixedVector.hpp
src/include/rho/LogicalVector.hpp
src/include/rho/UnaryFunction.hpp

In VectorOps, when a unary or binary function returns a scalar logical
value and the operand(s) don't have any attributes, return one of the
pre-allocated scalar logical values (R_TrueValue, R_FalseValue,
R_LogicalNAValue).

More use of R_TrueValue and R_FalseValue.

---

bench/report.R

* Rotated the benchmark labels in benchmark report graphs so more
commits can fit in a single graph.
* Disabled the tabular output because it doesn't fit in PDF pages
for many benchmarked commits.
* Added separate graphs for the geometric mean of results from the
benchmark groups riposte, shootout, scalar.

Adjust benchmark reports for many commits

---

src/main/jit/Compiler.cpp
src/main/jit/Optimization.cpp

Replaced uses of dynamic_cast<> by llvm-specific casts and type checks
where possible.

Replace dynamic_cast by llvm::dyn_cast / llvm::isa

---

.travis.yml

The LLVM apt repo is currently down, causing these to fail even if the code is correct.

Make all llvm 3.8 builds allowed failures on travis

---

src/main/GCNode.cpp

There is always at least one object in a GC block, but
applyToAllAllocatedNodesInBlock could skip an object if the object size
was greater than HBLKSIZE.

Fix error in live object iteration

---

src/main/RObject.cpp
src/main/WeakRef.cpp
src/main/coerce.cpp
src/main/eval.cpp

* Fixed type errors for two local variable declarations in
RObject::Transmute().
* Removed a few redundant if-statements testing NAMED saturation before
setting the NAMED field to the saturated value.

Small changes to NAMED handling

---

src/library/tools/src/gramLatex.c
src/main/gram.cpp
src/main/gram.y

The parser allocated new scalars for each "TRUE", "FALSE" and "NA". This
makes the parser instead call ScalarLogical() which reuses global scalar
logicals.

Avoid creating new logicals in parser

---

bench/report.R
bench/runbench.py

JIT benchmarking now compiles rho with Clang, which is required for
enabling the LLVM JIT compiler.
Added a few options to the runbench.py script: --skip-cr, --skip-jit,
and --no-clean.

Improve benchmark script, fix JIT benchmarking

---

src/include/rho/GCNode.hpp
src/main/GCNode.cpp

Renamed m_rcmms to the more descriptive name m_refcount_flags.
Fixed an error in a comment for the GCNode::s_decinc_refcount array.

Rename GCNode:m_rcmms to m_refcount_flags

---

bench/.gitignore
bench/allocbench.py
bench/allocbench/allocator_test.cpp
bench/allocbench/huge-lookup.R
bench/allocbench/huge-recursive.R
bench/allocbench/huge-reuse.R
bench/allocbench/huge.R
bench/allocbench/large-lookup.R
bench/allocbench/large-recursive.R
bench/allocbench/large-reuse.R
bench/allocbench/large.R
bench/allocbench/medium-recursive.R
bench/allocbench/medium-reuse.R
bench/allocbench/medium.R
bench/allocbench/small-lookup.R
bench/allocbench/small-recursive.R
bench/allocbench/small-reuse.R
bench/allocbench/small.R
bench/benchmark.py
bench/runbench.py

Added two new options to the benchmark script:
* --timestamp allows manually specifying the timestamp for the
benchmarked version.
* --no-build skips building Rho before running a benchmark. Useful when
re-running the benchmark for a single version.
This also adds new benchmarks for benchmarking the Rho allocator.

Add allocator benchmarks + more benchmark options

---

src/include/rho/ArgMatcher.hpp
src/include/rho/Closure.hpp
src/include/rho/GCNode.hpp
src/include/rho/RObject.hpp
src/main/ArgMatcher.cpp
src/main/Closure.cpp
src/main/GCNode.cpp
src/main/RObject.cpp

This is an experimental implementation of coalesced reference counting. It is not fit for production yet, but could be polished up if it turns out to be worthwhile.
This implementation steals one bit from the reference count to use as a dirty bit.
Coalescing the reference count for a reference involves the following changes:
* Change the declared field type from `GCEdge<X>` to `X*`
* Change the initial assignment (in the constructor) to `attachReference(x, initialRef)`
* Change any other assignment to `retargetReference(x, newTarget)`
* Replace all calls `x.get()` by a regular access: `x`
* Replace all calls `x.detach()` by `detachReference(x)`
* Override `applyToCoalescedReferences()` in the owner of the reference so that it calls the argument function on the coalesced reference.
The …

Experimental coalesced reference counting

---

src/include/R.h
src/include/R_ext/Arith.h
src/include/Rmath.h0.in
src/library/utils/src/io.cpp
src/main/GCManager.cpp
src/main/ListFrame.cpp
src/main/arithmetic.cpp

For C++ code that #include's <cmath>, ::isnan and ::isfinite
might not exist.  This change should fix compilation issues on those
platforms.

Cleanup use of isnan() and isfinite()

---

src/include/rho/ArgList.hpp
src/include/rho/ArgMatcher.hpp
src/main/ArgList.cpp
src/main/ArgMatcher.cpp
src/main/match.cpp

The vast majority of function calls in R code don't use named arguments.
In that case, argument matching can be made much simpler and faster.

Optimize matching of unnamed argument lists.
